### ISSUE TITLE
Clone requests between "On Behalf of a User" folder and "Application" folder

### ISSUE THREAD

**Issue by adsfjhbsdjfhbdsjfhb** [microsoftgraph/microsoftgraph-postman-collections#49]
Hi.

We're a SAAS company and use hundreds of customer azure apps when querying stuff through postman.

At the moment we are having to change the auth variable in all the "On behalf of a user" requests to {{AppAccessToken}} because we never have user accounts on our customers' tenants but we do have all power azure apps that have access to everything.

Could you guys please just clone the requests from the first folder into the second one since the requests work with the {{AppAccessToken}} as well so there's no real reason to not add them in to be honest since both the usernam that's a full admin and an all-powerful azure app would have the same permissions to run all the requests.

Thanks.

**Comment by jthake** [comment]
We are actually waiting on Postman to fix something to improve the auth configuration of our collection. Right now you cannot set one folder of requests up with one auth config and another with a different one. Once this happens, there are a few options on how we change this colelction and how it works.

It is not as simple as just copying the requests from delegated to application permissions. Because in a lot of cases, requests are not supported in application permissions. Also the scenario of chaining requests together is different as /me won't work on application permissions and /users/{user-id} is. That is why they are separated.

This collection is meant to be a way of exploring the APIs and you should take them and configure your own collection to your own business scenarios.

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
> We are actually waiting on Postman to fix something to improve the auth configuration of our collection. Right now you cannot set one folder of requests up with one auth config and another with a different one. Once this happens, there are a few options on how we change this colelction and how it works.
> 
> It is not as simple as just copying the requests from delegated to application permissions. Because in a lot of cases, requests are not supported in application permissions. Also the scenario of chaining requests together is different as /me won't work on application permissions and /users/{user-id} is. That is why they are separated.
> 
> This collection is meant to be a way of exploring the APIs and you should take them and configure your own collection to your own business scenarios.

Hi @jthake-msft .

Please don't close issues until the caller has had a chance to reply.

I obviously know that the request links are different, but what I meant was the actual APIs themselves.

We all know that most of the "on behalf of a user" apis work if used with the applications, however, you guys haven't added all the ones that work in the applications folder.

We also can't customise this for our business, because, every time you guys release more api calls we have to reimport the collection which then wipes out all of our changes.


What I'm saying is that you guys should just create calls for all apis that work as part of an application inside the application folder as well, not just inside the ones for the user account.

Applications have the same permission scope as a user would, so, to be honest, I see no reason why the exact same total number of calls shouldn't work as an application when they do on behalf of a user.

You may want to check that with the team that makes the APIs, because, tbh, I'd expect them to work just as well.

At a different call link of course, but still the same APIs.
